"""Renamed is_special_allocation to is_de_allocation

Revision ID: 0312afb603ef
Revises: 1f74846015b8
Create Date: 2025-09-02 12:32:36.801397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0312afb603ef'
down_revision = '1f74846015b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_de_allocation', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_special_allocation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special_allocation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('is_de_allocation')

    # ### end Alembic commands ###
