"""Added semester_id column to course-allocation table

Revision ID: 0afbbc20f37b
Revises: a3f44c4815fd
Create Date: 2025-07-02 09:57:20.347586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afbbc20f37b'
down_revision = 'a3f44c4815fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'semester', ['semester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###
