"""added a flag for determining when an allocation has been sent to umis

Revision ID: 11241cdc6231
Revises: d7102eaedb34
Create Date: 2025-12-09 21:03:00.774843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11241cdc6231'
down_revision = 'd7102eaedb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pushed_to_umis', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('superadmin', 'admin', 'vetter', 'hod', 'lecturer'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('superadmin', 'admin', 'vetter', 'hod', 'lecturer'),
               nullable=True)

    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_column('is_pushed_to_umis')

    # ### end Alembic commands ###
