"""Added School, Lecturer; link User to Lecturer; update CourseAllocation

Revision ID: 4e460e84cabe
Revises: d2f730d0a88e
Create Date: 2025-06-30 18:35:19.410337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e460e84cabe'
down_revision = 'd2f730d0a88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lecturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_allocation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lecturer', ['lecturer_id'], ['id'])

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'school', ['school_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['lecturer_id'])
        batch_op.create_foreign_key(None, 'lecturer', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lecturer_id')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_allocation_ibfk_1'), 'user', ['lecturer_id'], ['id'])

    op.drop_table('lecturer')
    op.drop_table('school')
    # ### end Alembic commands ###
