"""Add vetting fields to allocation state table

Revision ID: 5b9967dac500
Revises: 005ef808dbf8
Create Date: 2025-10-30 12:25:12.986057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9967dac500'
down_revision = '005ef808dbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_allocation_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vetted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('vetted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vetted_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['vetted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_allocation_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vetted_by_id')
        batch_op.drop_column('vetted_at')
        batch_op.drop_column('is_vetted')

    # ### end Alembic commands ###
