"""updated school, department, program, lecturer and course models with new fields

Revision ID: 672b3ca06efa
Revises: b885f157de26
Create Date: 2025-07-15 13:03:24.744037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672b3ca06efa'
down_revision = 'b885f157de26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.String(length=10), nullable=True))

    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('other_responsibilities', sa.String(length=100), nullable=True))

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.String(length=10), nullable=True))

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('acronym')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('acronym')

    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.drop_column('other_responsibilities')
        batch_op.drop_column('specialization')
        batch_op.drop_column('gender')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('acronym')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
