"""Add DepartmentAllocationState model with semester

Revision ID: 714ab36463bc
Revises: 1584200ca70f
Create Date: 2025-09-23 09:35:46.422135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714ab36463bc'
down_revision = '1584200ca70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_allocation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['academic_session.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'session_id', 'semester_id', name='_department_session_semester_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_allocation_state')
    # ### end Alembic commands ###
