"""updated user model for flexibility between admin users and hod's/lecturers

Revision ID: 717650afe20b
Revises: 672b3ca06efa
Create Date: 2025-07-16 15:38:54.397282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '717650afe20b'
down_revision = '672b3ca06efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('superadmin', 'vetter', 'hod', 'lecturer', name='user_roles'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('superadmin', 'vetter', 'hod', 'lecturer', name='user_roles'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
