"""Added units field in course table, and removed it from program-course table

Revision ID: 90b177a15e85
Revises: 0afbbc20f37b
Create Date: 2025-07-02 10:03:34.366462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90b177a15e85'
down_revision = '0afbbc20f37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.Integer(), nullable=True))

    with op.batch_alter_table('program_course', schema=None) as batch_op:
        batch_op.drop_column('units')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('units')

    # ### end Alembic commands ###
