"""Added class options column to course allocation table

Revision ID: b501c0e45514
Revises: eab47c38cec6
Create Date: 2025-11-07 12:17:01.411044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b501c0e45514'
down_revision = 'eab47c38cec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_option', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_column('class_option')

    # ### end Alembic commands ###
