"""added class_size field to the course allocation table

Revision ID: b885f157de26
Revises: 90b177a15e85
Create Date: 2025-07-07 12:26:43.055864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b885f157de26'
down_revision = '90b177a15e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_column('class_size')

    # ### end Alembic commands ###
