"""Add audit trail for UMIS push to CourseAllocation

Revision ID: c77ba5335823
Revises: 11241cdc6231
Create Date: 2025-12-10 09:02:22.818672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77ba5335823'
down_revision = '11241cdc6231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pushed_to_umis_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pushed_to_umis_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['pushed_to_umis_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pushed_to_umis_at')
        batch_op.drop_column('pushed_to_umis_by_id')

    # ### end Alembic commands ###
