"""Added group_name for grouping functionality  and is_lead to CourseAllocation

Revision ID: cc3f306613e5
Revises: 559b29759d83
Create Date: 2025-06-30 13:25:03.354211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3f306613e5'
down_revision = '559b29759d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_lead', sa.Boolean(), nullable=True))
        # batch_op.drop_index(batch_op.f('uq_programcourse_session'))
        batch_op.create_unique_constraint('uq_allocation_group', ['program_course_id', 'session_id', 'group_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_allocation_group', type_='unique')
        batch_op.create_index(batch_op.f('uq_programcourse_session'), ['program_course_id', 'session_id'], unique=True)
        batch_op.drop_column('is_lead')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
