"""Finalized models: added bulletin and special allocation support

Revision ID: d2f730d0a88e
Revises: cc3f306613e5
Create Date: 2025-06-30 17:13:31.470706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f730d0a88e'
down_revision = 'cc3f306613e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special_allocation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source_bulletin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_programcourse_session'))
        batch_op.create_foreign_key(None, 'bulletin', ['source_bulletin_id'], ['id'])

    with op.batch_alter_table('program_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulletin_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'bulletin', ['bulletin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('bulletin_id')

    with op.batch_alter_table('course_allocation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('uq_programcourse_session'), ['program_course_id', 'session_id'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('source_bulletin_id')
        batch_op.drop_column('is_special_allocation')

    op.drop_table('bulletin')
    # ### end Alembic commands ###
